### ISSUE TITLE
Factions Progress Tracker Part 1

### ISSUE THREAD

**Issue by Khaoz-Topsy** [AssistantNMS/App#12]
# _This issue was partially completed, a [new issue](https://github.com/AssistantNMS/App/issues/16) was created to continue the work_

**Describe the solution you'd like**
I would like a page where I can see what what will improve my standing with a Faction or Guild.

### Preparation: 
- [x] Figure out how to get list of Guild missions

### Actual Dev:
- [x] Page that lists Factions and Guilds
- [x] Lock behind Patreon exclusive
- [ ] Details page of that Faction/Guild
  - [x] Logo
  - [x] Description of that Guild/Faction
  - [x] List of options to improve standing (see images below)
  - [x] On tap, show modal like Journey Milestones, A list of the ranks and corresponding images
  - [ ] Guild specific details:
    - [ ] On clicking "Missions Completed" option show page of Guild Missions
      - [ ] Guild Missions List page
        - [ ] Each tile shows Mission type icon (blue icon)
        - [ ] Title (which goes through all the possibilities)
        - [ ] Subtitle: Mission objective
        - [ ] Trailing: Which Guild factions this is for (could be one or more up until 3)

### Additional context
![image](https://user-images.githubusercontent.com/15005470/157476488-775047e6-07c0-49e5-b2b5-5353792002d3.png)
![image](https://user-images.githubusercontent.com/15005470/157476534-b69bea4f-7dc5-4b62-a215-e11cf28411e9.png)
![image](https://user-images.githubusercontent.com/15005470/157477628-254db0c6-1e66-43f6-a74c-118d0bedf12b.png)
